### ISSUE TITLE
maSMP profiles

### ISSUE THREAD

**Issue by Dhwanisolanki12** [zbmed-semtec/maSMPs#11]
Upcoming tasks:

- [ ] Update the SoftwareMangPlans.jsonld profile by adding the properties from OutputMngPlans.
- [ ] Update the all the profiles files as discussed in the meeting.
- [ ] Create `readme.md` where all the combined profiles represented as separate table for each class. 
- [ ] In the readme, all the required, optional and recommended properties will be in the separate table.

**Comment by ljgarcia** [comment]
@Dhwanisolanki12 I kind of think this was done a long ago, was not it? Please update the issue. Thanks
