### ISSUE TITLE
User story: Create first MKDocs page with basic info of the project

### ISSUE THREAD

**Issue by ljgarcia** [zbmed-semtec/maSMPs#5]

**Comment by ljgarcia** [comment]
As a researcher, I would like to find a web page about the maSMP project. I expect to see a description, people involved, funding and links to related publications.
- [ ] Create such a page using MKDocs style
- [ ] Deploy to GitHub pages
- [ ] Upload gh-pages branch

**Comment by ljgarcia** [comment]
As a developer, I want to be able to run mkdocs locally. Without a requirements.txt, I have to try, guess and retry what extensions I need. 
- [ ] Add requirements.txt so all the extensions are easily installed for the mkdocs commands to be run locally.

**Comment by ljgarcia** [comment]
I have mkdoc installed and can run the `mkdoc serve` command in a project that does not use any extension. It does not work in this repo. I already installed the pymdown extensions but still does not work.

**Comment by Dhwanisolanki12** [comment]
its `mkdocs serve`. Because mkdocs.yml file contains all the requirements for mkdocs. Let me try it and I will get back to you by tomorrow.

**Comment by ljgarcia** [comment]
Locally working now, I am setting up the GH pages, let's see how it works.

**Comment by ljgarcia** [comment]
@Dhwanisolanki12 the GH pages are already set up in the repo but the gh-pages branch has not been created by the GH CI workflow that you defined. Please have a look. An option would be to move it to GH Actions. Have a look to the set up of GH pages with GH Actions in https://github.com/zbmed-semtec/zbmed-semtec.github.io (docs folder and mkdocs.yml file).

**Comment by ljgarcia** [comment]
Sorted out. Pages are now working.
I am closing this issue but for future updates, please keep the About page always as the last one. Thanks.
